---

- name: Install mariadb
  yum:
    name: "{{ mariadb_package }}"
    state: present

- name: Install mariadb_ansible_packages, required by ansible
  yum:
    name: "{{ mariadb_ansible_packages }}"

- name: Enable mariadb
  service:
    name: "{{ mariadb_service }}"
    enabled: yes

- name: Create systemd conf file directory
  file:
    path: "/etc/systemd/system/{{ mariadb_service }}.service.d"
    state: directory

- name: Create systemd conf file
  template:
    src: RedHat.systemd.conf.j2
    dest: "/etc/systemd/system/{{ mariadb_service }}.service.d/default.conf"
  register: __systemd_mariadb_conf
  notify:
    - Restart mariadb

- name: Run systemd daemon_reload
  command: systemctl daemon-reload
  when: __systemd_mariadb_conf.changed
