---
# tasks file for ansible-role-mariadb

- include_vars: "{{ ansible_os_family }}.yml"

- include: "install-{{ ansible_os_family }}.yml"

- name: Create log directory
  file:
    path: "{{ mariadb_log_dir }}"
    mode: 0755
    owner: "{{ mariadb_user }}"
    group: "{{ mariadb_group }}"
    state: directory
  notify: Restart mariadb

- name: Create db directory
  file:
    path: "{{ mariadb_db_dir }}"
    mode: 0755
    owner: "{{ mariadb_user }}"
    group: "{{ mariadb_group }}"
    state: directory
  notify: Restart mariadb

- name: Create mariadb.conf
  template:
    src: mariadb.conf.j2
    dest: "{{ mariadb_conf_file }}"
    validate: echo %s
  notify: Restart mariadb

- name: Start mariadb
  service:
    name: "{{ mariadb_service }}"
    enabled: true
    state: started
