---

- name: "Include vars/{{ ansible_os_family }}.yml"
  include_vars: "{{ ansible_os_family }}.yml"

- name: "Include tasks/install-{{ ansible_os_family }}.yml"
  include: "install-{{ ansible_os_family }}.yml"

- name: Create mariadb_conf_dir
  file:
    path: "{{ mariadb_conf_dir }}"
    mode: 0755
    state: directory

- name: Create mariadb.conf
  template:
    src: my.cnf.j2
    dest: "{{ mariadb_conf_file }}"
  notify: Restart mariadb

- name: Create mariadb_log_dir
  file:
    path: "{{ mariadb_log_dir }}"
    owner: "{{ mariadb_user }}"
    group: "{{ mariadb_group }}"
    mode: 0755
    state: directory
  # do not do anything with system log directory.
  when: mariadb_log_dir != '/var/log'
  notify:
    - Restart mariadb

- name: Start mariadb
  service:
    name: "{{ mariadb_service }}"
    enabled: true
    state: started

- name: Wait for mariadb
  wait_for:
    port: 3306

- name: Do flush_handlers
  meta: flush_handlers

- name: "Include set-root-password-{{ mariadb_family }}-{{ ansible_os_family }}.yml"
  include_tasks: "set-root-password-{{ mariadb_family }}-{{ ansible_os_family }}.yml"

- name: Create database users
  mysql_user:
    append_privs: "{{ item.append_privs | default(omit) }}"
    ca_cert: "{{ item.ca_cert | default(omit) }}"
    check_implicit_admin: "{{ item.check_implicit_admin | default(omit) }}"
    client_cert: "{{ item.client_cert | default(omit) }}"
    client_key: "{{ item.client_key | default(omit) }}"
    config_file: "{{ item.config_file | default(omit) }}"
    connect_timeout: "{{ item.connect_timeout | default(omit) }}"
    encrypted: "{{ item.encrypted | default(omit) }}"
    host: "{{ item.host | default(omit) }}"
    host_all: "{{ item.host_all | default(omit) }}"
    login_host: "{{ item.login_host | default(omit) }}"
    login_password: "{{ item.login_password | default(mariadb_root_password) }}"
    login_port: "{{ item.login_port | default(omit) }}"
    login_unix_socket: "{{ item.login_unix_socket | default(omit) }}"
    login_user: "{{ item.login_user | default(omit) }}"
    name: "{{ item.name }}"
    password: "{{ item.password | default(omit) }}"
    priv: "{{ item.priv | default(omit) }}"
    sql_log_bin: "{{ item.sql_log_bin | default(omit) }}"
    state: "{{ item.state | default(omit) }}"
    update_password: "{{ item.update_password | default(omit) }}"
  with_items: "{{ mariadb_users }}"

- name: Create .my.cnf for local users
  template:
    src: user.my.cnf.j2
    dest: "{{ item.path }}"
    mode: 0600
    owner: "{{ item.user }}"
  with_items: "{{ mariadb_my_cnf_files }}"
