---

- name: Test if /root/.my.cnf exist
  stat:
    path: /root/.my.cnf
  register: __root_my_cnf

- name: Set root password
  command:
    cmd: "mysql -uroot --batch -s -e \"UPDATE mysql.user SET Password=PASSWORD('{{ mariadb_root_password }}') WHERE User='root'; FLUSH PRIVILEGES;\""
  when:
    - not __root_my_cnf.stat.exists

- name: Create /root/.my.cnf
  template:
    src: user.my.cnf.j2
    dest: /root/.my.cnf
    mode: 0600
  with_items: "[ {{ mariadb_root_conf }} ]"
