---

- name: Restart mariadb
  service:
    name: "{{ mariadb_service }}"
    state: restarted
  notify:
    - Wait for mariadb

- name: Wait for mariadb
  wait_for:
    delay: 5
    port: 3306

- name: Reload systemd
  systemd:
    daemon_reload: yes
