---

- name: Restart mariadb
  service:
    name: "{{ mariadb_service }}"
    state: restarted
  notify:
    - Wait for mariadb

- name: Wait for mariadb
  wait_for:
    delay: 5
    port: "{{ mariadb_port }}"
    host: "{{ mariadb_host }}"

- name: Reload systemd
  command: systemctl daemon-reload
